openapi: 3.0.0

info:
  title: API
  version: 0.1.0

paths:
  '/foo':
    get:
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  foo:
                    type: string

