/*
 * API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type FooGet200Response struct {

	Foo string `json:"foo,omitempty"`
}

// AssertFooGet200ResponseRequired checks if the required fields are not zero-ed
func AssertFooGet200ResponseRequired(obj FooGet200Response) error {
	return nil
}

// AssertRecurseFooGet200ResponseRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of FooGet200Response (e.g. [][]FooGet200Response), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseFooGet200ResponseRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aFooGet200Response, ok := obj.(FooGet200Response)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertFooGet200ResponseRequired(aFooGet200Response)
	})
}
